### ISSUE TITLE
OpenCV Module

### ISSUE THREAD

**Issue by MassimilianoLuca** [giovcandido/prototypical-networks-project#2]
Hello! I tried to run your code and I got the following error: 

`ModuleNotFoundError: No module named 'cv2'`

This can be solved with the following commands: 

`pip install scikit-build` 
`pip install opencv-python` 

Maybe such packages can be added to the dependencies. Thanks for your work!

**Comment by giovcandido** [comment]
Hi! I'm glad to know you found my code.

There's a script that installs the requirements for you. It's the __install_deps.sh__.

This script already has the __opencv-python__ package.

Did you need to install the __scikit-build__ package to run the code?

If so, it should be added to the requirements as well.

Thank you for your feedback. It's good to know you liked my work.

**Comment by MassimilianoLuca** [comment]
Correct, sorry. It was not clear from the issue. I used the script to install the dependencies but I also had to install `scikit-build`. Also, it should be installed before opencv: https://stackoverflow.com/questions/63448467/installing-opencv-fails-because-it-cannot-find-skbuild

**Comment by giovcandido** [comment]
Alright! I added scikit-build to the requirements.

Was it the only additional package you needed to install?

**Comment by giovcandido** [comment]
In case there are more packages that need to be added to the requirements, reopen this issue.

I'm closing it for now.

Once again, thanks for the help! ;)
