### ISSUE TITLE
Dataset access

### ISSUE THREAD

**Issue by CJR7** [giovcandido/prototypical-networks-project#6]
Hello! Thank you for your sharing! May I kindly ask for access to the Google drive that contains datasets?

**Comment by giovcandido** [comment]
Hello! I need to update the dataset downloader script. But, in the meantime, you can manually download the datasets here: https://drive.google.com/drive/folders/1Kr5ednqPyilQIUNwIZbS04WBGfSLsiWV?usp=drive_link.

**Comment by CJR7** [comment]
Thank you so much!
